### ISSUE TITLE
Auth redirects for loggedOut state

### ISSUE THREAD

**Issue by GarrySan** [swd-bits-goa/swd_django#104]
When the Profile option is clicked inside the sidebar while the user is logged out the user must be redirected to the login page but currently its going to a blank page.

**Comment by GarrySan** [comment]
#105

**Comment by prampey** [comment]
This can be handled at the router level itself. https://reacttraining.com/react-router/web/example/auth-workflow

**Comment by prampey** [comment]
We'll have to make 'login' a route though.

**Comment by GarrySan** [comment]
Did you see the commit I made? I am using the isLoggedIn prop to conditionally render stuff

**Comment by prampey** [comment]
Yes but you cannot use that everywhere right? There will be other private routes which can only be accessed by logged-in user. We shouldn't have to write extra code for conditional rendering in each one of them. Best to let the router take care with the help of _conditional routing_.
Also, the job of the Sidebar is just to route to the corresponding link, not to dabble in the applications' logged-in state.

**Comment by GarrySan** [comment]
Guess we will have to scrap #105 then

**Comment by prampey** [comment]
Yeah sorry.

**Comment by prampey** [comment]
#107 is required to redirect user to login page.
