### ISSUE TITLE
Footer with developer link

### ISSUE THREAD

**Issue by aryanagarwal15** [swd-bits-goa/swd_django#125]
I searched a little and found out that there are many responsive react web apps that employ footer to give credit to developers. Heck even the official Material UI page have a footer (shown below).

![7878](https://user-images.githubusercontent.com/28765515/38318558-39f21658-384d-11e8-8e0e-fa96c253ddf3.png)

I suggest that we also change the footer to show credits to developers.
@prampey @GarrySan What are your views on this?

**Comment by prampey** [comment]
Yes I think we should do this. But lets leave it only for logged out users or basically whenever someone visits the website initially.

**Comment by aryanagarwal15** [comment]
Needn't be done
