### ISSUE TITLE
No leave and mess option for PhD students

### ISSUE THREAD

**Issue by sarthakag** [swd-bits-goa/swd_django#133]
Have to block the leave and mess option tabs for PhD Students

**Comment by sarthakag** [comment]
Their supervisor takes care of leaves and they have a register for mess.

**Comment by mehulmpt** [comment]
How to recognize PhD students? Regex for their roll number is ..?

**Comment by mehulmpt** [comment]
*2016* always?

**Comment by SebastinSanty** [comment]
Nope

**Comment by mehulmpt** [comment]
**20\d{2}PHX[PH]\d{3,4}G** 


Should work for 82 years
