### ISSUE TITLE
Automatic redirection to dashboard on hitting /login/ if logged in

### ISSUE THREAD

**Issue by SebastinSanty** [swd-bits-goa/swd_django#141]

**Comment by mehulmpt** [comment]
Fixed in #129

**Comment by SebastinSanty** [comment]
Oh, I am sorry :(. Is it possible for you to make a new PR? I kinda completed the whole store thing as we were running out of time on Sunday.

**Comment by SebastinSanty** [comment]
I did review it locally, but it wasn't completed. I did ping on Sunday, but upon no response, I had to take it up and finish it by myself.
