### ISSUE TITLE
Session expiry management

### ISSUE THREAD

**Issue by prampey** [swd-bits-goa/swd_django#145]
It looks like the GraphQL API currently returns empty queries when the authorization JWT token expires. There is currently no way for the client to know that the token has expired. A longstanding webpage on a computer might have its session expired with no prompt to user about login or expiry.
I think we should return a GraphQL error stating that the token has expired. This will allow us to ask the user to login again.

**Comment by aryanagarwal15** [comment]
Needn't be done
