### ISSUE TITLE
Bonafide cosmetic changes

### ISSUE THREAD

**Issue by sarthakag** [swd-bits-goa/swd_django#156]
1. Other reason length to be 200 and should be shown as a separate paragraph.
2. Reference no & date should come in one line.
3. Reference no & date format as shown below
4. Main content needs to be changed as shown below
5. Increase the font  size
6. Mention the associate dean's name in bracket.

![cert](https://user-images.githubusercontent.com/8204356/39156290-19de76c4-4773-11e8-83a4-6e39edb21fb8.png)

**Comment by mehulmpt** [comment]
What is this?
