### ISSUE TITLE
Dues upload page extend bug

### ISSUE THREAD

**Issue by sarthakag** [swd-bits-goa/swd_django#193]
The due upload page(/dues_dashboard/) directs the admin to student home(extends base.html), where the admin has no role.

**Comment by khizirsiddiqui** [comment]
@ashadhaz I think this issue got fixed in some PR.

**Comment by aryanagarwal15** [comment]
@ashadhaz can you confirm if this bug is resolved as mentioned by Khizir? If yes, close this
