### ISSUE TITLE
CSA page alignment

### ISSUE THREAD

**Issue by ashadhaz** [swd-bits-goa/swd_django#229]
The third member of CSA is not in correct position when tested in Google Chrome

**Comment by Aviral09** [comment]
This issue is no longer there in the updated code in #282

**Comment by khizirsiddiqui** [comment]
@Aviral09 is the layout consistent in Chrome, now?

**Comment by Aviral09** [comment]
Yeah I've been using chrome and the layout is fine with dummy data.

**Comment by Aviral09** [comment]
<img width="960" alt="CSAmembers" src="https://user-images.githubusercontent.com/59691764/88428174-f8134600-ce11-11ea-836b-8e49b68f8252.png">
Updated Sample Layout

**Comment by khizirsiddiqui** [comment]
Thanks for testing on chrome, I will close this then.
