### ISSUE TITLE
Security needs login credentials 

### ISSUE THREAD

**Issue by ashadhaz** [swd-bits-goa/swd_django#231]
Security dashboard needs to be displayed when the security logs in. Currently there is no login for the main gate.

**Comment by aryanagarwal15** [comment]
@ashadhaz lets put this on hold as of now. I'm creating labels and issues based on our conversation ealier

**Comment by ashadhaz** [comment]
Actually if this is on hold then there won't be any way for the security to check if the student is on leave. We already have a dashboard, but it's open to all. Just need to add a user for security

**Comment by aryanagarwal15** [comment]
Ok, I'll change tags accordingly.
