### ISSUE TITLE
Change email sent to personal email to BITS email

### ISSUE THREAD

**Issue by aryanagarwal15** [swd-bits-goa/swd_django#241]
Request by SWD dep. personal emails provided by students may not be correct.

@ashadhaz please assign the issue to someone on high priority.

**Comment by khizirsiddiqui** [comment]
@ashadhaz this got resolved in [this commit](https://github.com/swd-bits-goa/swd_django/commit/a00d74ca0010766855eb184702809e7df12b1974), if I am not wrong. We can close this now, I guess.

**Comment by aryanagarwal15** [comment]
@khizirsiddiqui you are right, this is resolved. closing it.
