### ISSUE TITLE
Change format of Bonafide Certificate

### ISSUE THREAD

**Issue by SebastinSanty** [swd-bits-goa/swd_django#72]
SWD has asked for a specific change, which I am not very sure of how exactly to implement:
Some of the words/phrases in the body of Bonafide has to be italic in order to highlight them.

I have two ideas of implementing this feature:
1) Create our minor version of templating. Say my name, `Sebastin` has to be italicized, then using some string literals around it we can parse and get to know that this has to be italicized. Eg. `((( Sebastin )))` will make my name italicized by replacing `(((` and `)))` with `<i>` and `</i>` respectively.

2) Use a Rich Text Editor like `django-tinymce` to put the body of the text.

The former idea is what I feel is best adapted to this situation. @sarthakag Any comments?

**Comment by sarthakag** [comment]
Instead of adding `((( )))`, the form field in django is capable of rendering html by using the template filter `safe`.
