### ISSUE TITLE
updateMessOption mutation might need some fixes

### ISSUE THREAD

**Issue by prampey** [swd-bits-goa/swd_django#79]
Currently, this mutation take Mess choice and Date as arguments. Date should not be taken for security reasons as the client-side clock can be easily fooled. Any particular user should only be able to provide mutations for the current month.
Also, the response payload comes with an ID on successful mutation. What is the significance of this?
Do we need to include an explicit 'success' boolean to make client-side processing easier?

**Comment by sharanry** [comment]
@prampey Where is this mutation present? I am unable to find it.

**Comment by prampey** [comment]
Note: In accordance with the messoption query in PR #97 , this mutation needs to update the mess option _in-place_ (if it already exists) rather than add a new mess option entry for a user.
This is because the messoption query returns null if there are more than 3 mess option objects for a user in a particular month.

**Comment by prampey** [comment]
@sharanry I will shortly push in the PR which has the mutation code.

**Comment by prampey** [comment]
@sharanry PR has been pushed to master.
