### ISSUE TITLE
Reload resubmits the form of leave and bonafide 

### ISSUE THREAD

**Issue by sarthakag** [swd-bits-goa/swd_django#84]
On reloading the page after submitting an application for leave and bonafide, the form is submitted again creating extra entry

**Comment by SebastinSanty** [comment]
Yes, good catch. We'll have to redirect to the same view again. This means we won't show a confirmation of the submission, but it will rather appear in the side panel.

**Comment by adi10197** [comment]
If no one's working on this already I'll take this.

**Comment by SebastinSanty** [comment]
Other forms also have this problem, like login page. Look into that too.
