### ISSUE TITLE
Make Logged In view for mobile

### ISSUE THREAD

**Issue by aryanagarwal15** [swd-bits-goa/swd_django#89]
Make Logged In page for mobile using React. Add graphQL queries to insert data to props.

**Comment by aryanagarwal15** [comment]
#88

**Comment by prampey** [comment]
I'll get to this as soon as I push in the mess option PR.

**Comment by aryanagarwal15** [comment]
#149 Please ignore previous pull request

**Comment by aryanagarwal15** [comment]
Needn't be done
